### ISSUE TITLE
静的変換メタデータ共通化初回版

### ISSUE THREAD

**Issue by saki7** [cpprefjp/kunai_config#1]
cc: @cpprefjp/design 

データの中身は現行のものから変更無しで、ファイルの形式を標準化しています。

仕様についてはWiki→ https://github.com/cpprefjp/kunai_config/wiki

これを元に、 [cpprefjp/site_generator](https://github.com/cpprefjp/site_generator) の既存のコードを置き換えます。

JavaScriptのリファレンス実装はここ→ https://github.com/cpprefjp/crsearch/blob/master/js/crsearch/kunai-config.js

cpprefjpの本番にデプロイが完了したらこれを完了とみなし、closeします。仕様レベルでの問題があればここのコメント欄に書いてください。

**Comment by saki7** [comment]
これは、もともと cpprefjp/site のようなリポジトリでまとめて管理していたものです。しかし、Gitにはファイル単位でのcloneなどが無く、純粋に開発の都合でリポジトリごと分離した方が楽という理由から今回の提案に至っています。

**Comment by saki7** [comment]
複数のリポジトリ間でどうやって同期を取るのかという問題がありますが、一番レイヤーが高いのが site_generator なので site_generator がどういう管理をするのかによります。

- 案1: kunai と site_generator で常に最新の submodule を持っておくことにして、バージョン違いは無視する（CIで検出して弾く）
- 案2: site_generator が kunai を clone する時に kunai の submodule を見に行く

この点についても開発上の都合なので、今の site_generator のコードベースに一番詳しい @melpon に決定を委ねたいと思います。

**Comment by saki7** [comment]
また、これは以下のように 

- cpprefjp/kunai_config
- boostjp/kunai_config （まだない）

として管理することを想定しているので、cloneする時に名前を `cpprefjp-kunai_config` などに自前で指定しないとファイルがかぶります

**Comment by saki7** [comment]
refs: cpprefjp/site_generator#28, cpprefjp/site_generator#35
maybe related to: cpprefjp/site_generator#30

**Comment by melpon** [comment]
> cloneする時に名前を cpprefjp-kunai_config などに自前で指定しないとファイルがかぶります

site_generator が元々 cpprefjp と boostjp の設定を持っていることを考えると、kunai_config に cpprefjp と boostjp 用のディレクトリを作って書くのでも良さそうです。

>    案1: kunai と site_generator で常に最新の submodule を持っておくことにして、バージョン違いは無視する（CIで検出して弾く）
>    案2: site_generator が kunai を clone する時に kunai の submodule を見に行く

二重にバージョンを管理とかしたくないので、案2にしましょう。

**Comment by saki7** [comment]
>> cloneする時に名前を cpprefjp-kunai_config などに自前で指定しないとファイルがかぶります
> 
> site_generator が元々 cpprefjp と boostjp の設定を持っていることを考えると、kunai_config に cpprefjp と boostjp 用のディレクトリを作って書くのでも良さそうです。

site_generator + kunai + crsearch のインフラを（cpprefjp, boostjp以外の）別のドキュメンテーションに利用する可能性を考えて、 kunai_config は独立可能にしようかなと思っています。

>> 案1: kunai と site_generator で常に最新の submodule を持っておくことにして、バージョン違いは無視する（CIで検出して弾く）
>> 案2: site_generator が kunai を clone する時に kunai の submodule を見に行く
>
> 二重にバージョンを管理とかしたくないので、案2にしましょう。

https://github.com/cpprefjp/kunai/compare/v1.2.0...v1.3.0

kunaiにsubmoduleで追加しておきました。site_generatorではこれを使い始めてOKです。

考えた末、 以下のような仕様にしようと思います。

- site_generator はまず kunai を clone する
- kunai/kunai_configs/cpprefjp が cpprefjp
- kunai/kunai_configs/boostjp が boostjp （まだない）
- kunai/kunai_configs/current →後述

kunaiにおけるcurrentの仕様

- kunai_configs 以下の cpprefjp と boostjp はデフォルトでバンドルする
- current が上記２つ以外を指している場合はそれも追加でバンドルする
- cpprefjp / boostjp 以外のドキュメンテーションをビルドする場合は、 current を参照する
- どのドキュメンテーションを対象にフロントエンドを構築するのかは現状では `kunai::cpprefjp()` か `kunai::boostjp()` で判断している

**Comment by saki7** [comment]
https://github.com/cpprefjp/kunai_config/issues/1#issuecomment-341832240 の補足

つまり、 cpprefjp / boostjp 以外のドキュメンテーションにこのインフラを使う場合、 site_generator で kunai/kunai_configs/current のシンボリックリンクを張り替えて npm run build 再実行すれば良いはずです。今はこういう物は無いのでこの辺は何も考えなくても良いんですが、まあ、いずれ。

**Comment by saki7** [comment]
フロントエンドではv2以降から完全にこれを使うようにしたので対応は完了

**Comment by saki7** [comment]
バックエンドは cpprefjp/site_generator#43
